# version: 0.2

# phases:
#   install:
#     commands: 
#       - echo Installing
#   pre_build:
#     commands:
#       - echo Pre-build phase
#   build:
#     commands:
#       - echo build phase
#   post_build:
#     commands:
#       - echo Post-build phase

# artifacts:
#   files:
#     - '**/*' # extract all files in this repository. 

# env:
#   variables:
#     MY_VAR: "value"

version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-credentials:username"
    SECRET_PASSWORD: "pipeline-docker-credentials:password"

phases:
  pre_build:
    commands:
     - echo Logging in to Dockerhub
     - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin


  build:
    commands:
      - echo "building docker image..."
      - docker build -t maxshen01/pottery-db:latest .
  
  post_build:
    commands:
     - echo "Pushing to docker image"
     - docker push maxshen01/pottery-db:latest
artifacts:
  files:
    - 'Dockerfile' 