# version: 0.2

# phases:
#   install:
#     commands: 
#       - echo Installing
#   pre_build:
#     commands:
#       - echo Pre-build phase
#   build:
#     commands:
#       - echo build phase
#   post_build:
#     commands:
#       - echo Post-build phase

# artifacts:
#   files:
#     - '**/*' # extract all files in this repository. 

# env:
#   variables:
#     MY_VAR: "value"

version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-credientials:username"
    SECRET_PASSWORD: "pipeline-docker-credientials:password"

phases:
  build:
    commands:
      - echo "Hello World from BuildSpec.yml"
      - echo "$SECRET_USERNAME"
artifacts:
  files:
    - 'Dockerfile' 